= Introduction to Red Hat OpenShift AI
:navtitle: Home

Welcome to this quick course on the _Introduction to Red Hat OpenShift AI_.
This course is the *first* in a series of *five* courses about Red Hat OpenShift AI:

1. Introduction to Red Hat OpenShift AI (_This course_)
2. https://redhatquickcourses.github.io/rhods-admin[Red Hat OpenShift AI Administration]
3. https://redhatquickcourses.github.io/rhods-model[Creating Machine Learning Models with Red Hat OpenShift AI]
4. https://redhatquickcourses.github.io/rhods-deploy[Deploying Machine Learning Models with Red Hat OpenShift AI]
5. https://redhatquickcourses.github.io/rhods-pipelines[Automation using Data Science Pipelines]

NOTE: After you have completed all the courses in the learning path, you can attempt the https://github.com/RedHatQuickCourses/rhods-qc-apps/tree/main/7.hands-on-lab["Workshop final hands-on lab"], that tests your understanding of the concepts taught in all the courses.

IMPORTANT: The hands-on labs in this course were created and tested with RHOAI v2.8.0. Labs should mostly work without any changes in minor dot release upgrades of the product. Please open issues in this repository if you face any issue.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Jaime Ramirez Castillo
* Trevor Royer
* Ravi Srinivasan

== Classroom Environment

This introductory course has a few, simple hands-on labs. You will use the https://demo.redhat.com/catalog?search=openshift+data+science&item=babylon-catalog-prod%2Fsandboxes-gpte.ocp4-workshop-rhods-base-aws.prod[Base RHOAI on AWS] catalog item in the Red Hat Demo Platform (RHDP) to run the hands-on exercises in this course.

When ordering this catalog item in RHDP:

* Select *Practice/Enablement* for the *Activity* field
* Select *Learning about the Product* for the *Purpose* field
* Enter *Learning RHOAI* in the *Salesforce ID* field
* Select the nearest AWS region in the *Region* field

For Red Hat partners who do not have access to RHDP, provision an environment using the https://console.redhat.com/application-services/data-science[Red Hat Hybrid Cloud Console^]. Unfortunately, the labs will NOT work on the trial sandbox environment. You need to provision an OpenShift AI cluster on-premises, or in the supported cloud environments by following the product documentation at https://access.redhat.com/documentation/en-us/red_hat_openshift_ai/2024[Product Documentation for Red Hat OpenShift AI 2024].

The other courses in the learning path use a different classroom. Inspect the prerequisites and 
classroom requirements in the respective individual courses.

== Prerequisites

For this introductory course, basic experience with Red{nbsp}Hat OpenShift is recommended but is not mandatory.

== Objectives

The overall objectives of this introductory course include:

* Familiarize with the general architecture and main features of Red{nbsp}Hat OpenShift AI
* Access and log in to the Red{nbsp}Hat OpenShift AI web console
* Create, share, and delete data science projects
* Create a workbench within a data science project
* Create and delete data connections
* Create, import (from Git repositories), and share Jupyter Notebook
* Install Python packages in your Jupyter Notebook
