site:
  title: Introduction to Red Hat OpenShift Data Science
  start_page: rhods-intro::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    experimental: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui